sonar.projectKey=JoaccoG_moviebox
sonar.organization=joaccog

sonar.projectName=moviebox
sonar.projectVersion=1.0

sonar.sourceEncoding=UTF-8

sonar.sources=./app

sonar.test.inclusions=app/**/*.test.ts, app/**/*.test.tsx
sonar.coverage.exclusions=app/**/*.d.ts, app/tests/**, app/layouts/**, app/routes/**, app/routes.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
