name: Testing

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Tests passes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: (>) Git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: (>) Set up node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: (>) Check secrets exist
        run: |
          if [[ -z "${{ secrets.VITE_OMDB_API_KEY }}" ]]; then
            echo "Error: VITE_OMDB_API_KEY no está definido."
            exit 1
          fi
          if [[ -z "${{ secrets.VITE_OMDB_BASE_URL }}" ]]; then
            echo "Error: VITE_OMDB_BASE_URL no está definido."
            exit 1
          fi
          echo "Secrets are defined."

      - name: (>) Set environment variables
        run: |
          echo "VITE_OMDB_API_KEY=${{ secrets.VITE_OMDB_API_KEY }}" >> $GITHUB_ENV
          echo "VITE_OMDB_BASE_URL=${{ secrets.VITE_OMDB_BASE_URL }}" >> $GITHUB_ENV

      - name: (>) Cache pnpm
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: (>) Install pnpm
        run: npm install -g pnpm

      - name: (>) Install dependencies
        run: pnpm install

      - name: (>) Create .env file
        run: |
          echo "VITE_OMDB_API_KEY=${{ secrets.VITE_OMDB_API_KEY }}" >> .env
          echo "VITE_OMDB_BASE_URL=${{ secrets.VITE_OMDB_BASE_URL }}" >> .env
          echo ".env file created."

      - name: (>) Run tests
        env:
          VITE_OMDB_API_KEY: ${{ secrets.VITE_OMDB_API_KEY }}
          VITE_OMDB_BASE_URL: ${{ secrets.VITE_OMDB_BASE_URL }}
        run: pnpm vitest --coverage
